---
- name: Check if xdxgpu_driver is installed
  become: yes
  command: dpkg -s xdxgpu
  register: driver_status
  ignore_errors: yes

- name: Copy the driver deb package
  copy:
    src: dist/xdxgpu_dkms_151-{{ ansible_distribution | lower }}_{{ ansible_machine | replace('x86_64', 'amd64') }}.deb
    dest: /tmp/xdxgpu_driver.deb
  when: driver_status.rc != 0

- name: Install the driver deb package
  become: yes
  command: dpkg -i /tmp/xdxgpu_driver.deb
  when: driver_status.rc != 0
  notify: Reboot the machine

- name: Install some related base packages
  become: yes
  become_user: root
  become_method: sudo
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - tar
    - wget
  environment: 
   http_proxy: "{{ http_proxy }}"
   https_proxy: "{{ http_proxy }}"

- name: Check if the docker is installed
  become: yes
  command: docker version
  register: docker_status
  ignore_errors: yes

- name: debug
  debug:
    var: "{{ ansible_machine }}"
  
- name: Copy the docker installation file
  copy:
    src: dist/docker-20.10.21-{{ ansible_machine | replace('x86_64', 'amd64') }}.tgz
    dest: /tmp/
    mode: 0755
  when: docker_status.rc != 0

- name: Copy the docker installtation script
  copy:
    src: docker_install_{{ ansible_machine }}.sh
    dest: /tmp/
    mode: 0755
  when: docker_status.rc != 0

- name: Install docker
  become: yes
  command: /tmp/docker_install_{{ ansible_machine }}.sh
  notify: 
    - Enable the docker
    - Restart the docker
  when: docker_status.rc != 0

- name: Check if docker.service exists
  become: yes
  stat:
    path: /lib/systemd/system/docker.service
  register: service_info

- name: Copy docker.service
  become: yes
  copy:
    src: docker.service
    dest: /lib/systemd/system/docker.service
    mode: 0644
  notify: 
    - Reload the daemon
    - Restart the docker
  when: not service_info.stat.exists

- name: Check if docker-compose is installed
  command: docker-compose version
  register: compose_status
  ignore_errors: yes

- name: Copy docker-compose
  become: yes
  copy: 
    src: dist/docker-compose.{{ ansible_machine }}
    dest: /usr/local/bin/docker-compose
    mode: 0755
  when: compose_status.rc != 0

- name: Check if the docker group exists
  become: yes
  group:
    name: docker
    state: present

- name: Check if the user in docker group
  become: yes
  user: 
    name: "{{ ansible_env.USER }}"
    groups: docker
    append: yes

- name: Query the hosts config if it needs to be changed
  shell: cat /etc/hosts | grep hub.xdxct.com
  register: hosts_status
  ignore_errors: yes

- name: Modification hosts file
  become: yes
  become_user: root
  # become_method: sudo
  command: sh -c 'echo "10.211.10.15 hub.xdxct.com" >> /etc/hosts'
  when: hosts_status.rc != 0

- name: Check if xdxct.com.crt exists
  become: yes
  stat:
    path: /etc/docker/certs.d/hub.xdxct.com/xdxct.com.crt
  register: file_info

- name: Create the hub.xdxct.com directory
  become: yes
  file:
    path: /etc/docker/certs.d/hub.xdxct.com
    state: directory
  when: not file_info.stat.exists

- name: Copy the repository crt
  become: yes
  copy:
    src: xdxct.com.crt
    dest: /etc/docker/certs.d/hub.xdxct.com/xdxct.com.crt
  when: not file_info.stat.exists
  notify: Restart the docker

- name: Login to the hub.xdxct.com
  shell: echo -e "Harbor12345" | docker login hub.xdxct.com

- name: Check if xdxct-container-runtime deb package is installed
  become: yes
  command: dpkg -s xdxct-container-runtime
  register: runtime_status
  ignore_errors: yes

- name: Check if the docker installer of xdxct-container-runtime is installed
  become: yes
  stat:
    path: /usr/local/xdxct/toolkit
  register: toolkit_status
  
- name: Distribute the xdxct container runtime installer
  copy:
    src: xdxct_runtime_installer.sh
    dest: /tmp/xdxct_runtime_installer.sh
    mode: 0755
  when: runtime_status.rc != 0 and not toolkit_status.stat.exists

- name: Execute the xdxct container runtime installer
  become: yes
  command: /tmp/xdxct_runtime_installer.sh {{ runtime_installer_image_deb }}
